### PR TITLE
Update/Review 2024 - Setup, Tutorial and Day 1

### PR DESCRIPTION
**Pull request by sadamov**
- Fixing `requirements.txt`, old gt4py commit was not available anymore. Updating some old packages in the meantime.
- Added `module load FFmpeg` to kernel for animated figures in tutorial
- Reran all solutions notebooks with the latest setup at Piz Daint
- Updates to most powerful super-computer section -> Frontier
- Added some solution-text and a Julia-notebook (for performance comparison)
- Removed some broken links to websites or private Youtube videos
- Correcting same typos

### CODE REVIEW

**Comment by sadamov** [comment]
I continue updating notebooks and pushing to this PR-branch. For Day 2 changes were smaller:
- Defaut for task and solutions is no FORTRAN (over C++)
- Generated all output for the solutions notebooks
- Updated runtimes (which for some reason are slightly slower than last year...?)
- Fixed various typos

**Comment by sadamov** [comment]
For day 3-4 there was little to update so I tried to solve the bonus questions instead and added my examples to the `.solutions`. I could only test on one GPU, as that seems to be the account limit.

**Comment by sadamov** [comment]
This PR now contains updates to all 5 days and is ready for merge + the course next week.

Day5: Had to ignore some `cxx` compiler warnings due to deprecated softwares stack. Other than that everything is still working great with the newer GT4PY version.

**Review by ofuhrer — APPROVED** [review]
Thank you for the extremely careful review and updating of the course material. Really awesome!

**Pull request merged**
